version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-mercado-livre
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:7.0-alpine
    container_name: redis-mercado-livre
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  cassandra:
    image: cassandra:latest
    container_name: cassandra-mercado-livre
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MercadoLivreCluster
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_PASSWORD_SEEDER=true
      - CASSANDRA_USERNAME=admin
      - CASSANDRA_PASSWORD=root
    volumes:
      - cassandra-data:/var/lib/cassandra

  neo4j:
    image: neo4j:5
    container_name: neo4j-mercado-livre
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/admin123
    volumes:
      - neo4j-data:/data

volumes:
  mongodb-data:
  redis-data:
  cassandra-data:
  neo4j-data:
