version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_mercado_livre
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
  redis:
    image: redis:7.0-alpine
    container_name: redis_mercado_livre
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongodb-data:
  redis-data:
